# Generated by Django 4.2.7 on 2023-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=255)),
                ('modelis', models.CharField(max_length=255)),
                ('nuo_kainos', models.PositiveIntegerField()),
                ('iki_kainos', models.PositiveIntegerField()),
                ('nuo_metai', models.DateField()),
                ('iki_metai', models.DateField()),
                ('kebulo_tipas', models.CharField(max_length=255)),
                ('kuro_tipas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paskyra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vartotojo_vardas', models.CharField(max_length=255)),
                ('slaptazodis', models.CharField(max_length=255)),
            ],
        ),
    ]
