# Generated by Django 4.2.7 on 2023-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='iki_kainos',
            field=models.PositiveIntegerField(help_text='Maksimali kaina.'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='iki_metai',
            field=models.DateField(help_text='Maksimalūs gamybos metai.'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='kebulo_tipas',
            field=models.CharField(help_text='Automobilio kebulo tipas.', max_length=255),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='kuro_tipas',
            field=models.CharField(help_text='Automobilio kuro tipas.', max_length=255),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='marke',
            field=models.CharField(help_text='Automobilio gamintojas.', max_length=255),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='modelis',
            field=models.CharField(help_text='Automobilio modelis.', max_length=255),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='nuo_kainos',
            field=models.PositiveIntegerField(help_text='Minimali kaina.'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='nuo_metai',
            field=models.DateField(help_text='Minimalūs gamybos metai.'),
        ),
    ]
