# Generated by Django 4.2.7 on 2023-11-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0002_alter_automobilis_iki_kainos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motociklas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(help_text='Motociklo gamintojas.', max_length=255)),
                ('modelis', models.CharField(help_text='Motociklo modelis.', max_length=255)),
                ('nuo_metai', models.DateField(help_text='Minimalūs gamybos metai.')),
                ('iki_metai', models.DateField(help_text='Maksimalūs gamybos metai.')),
                ('cm3_nuo', models.PositiveIntegerField(help_text='Minimali darbinė talpa (cm³).')),
                ('cm3_iki', models.PositiveIntegerField(help_text='Maksimali darbinė talpa (cm³).')),
                ('motociklo_tipas', models.CharField(help_text='Motociklo tipas.', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Paskyra',
        ),
    ]
