# Generated by Django 4.2.7 on 2023-11-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0003_motociklas_delete_paskyra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportoTipas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipas', models.CharField(help_text='Pasirinkite transporto tipa', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='automobilis',
            name='tipas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarSell.transportotipas'),
        ),
    ]
