# Generated by Django 4.2.7 on 2023-11-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0004_transportotipas_automobilis_tipas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportotipas',
            name='tipas',
            field=models.CharField(choices=[('automobilis', 'Automobilis'), ('motociklas', 'Motociklas')], help_text='Pasirinkite transporto tipa', max_length=255),
        ),
    ]
