# Generated by Django 4.2.7 on 2023-11-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0005_alter_transportotipas_tipas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilis',
            name='tipas',
        ),
        migrations.DeleteModel(
            name='TransportoTipas',
        ),
    ]
