# Generated by Django 4.2.7 on 2023-11-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0007_client_detail_payment_rentalcontract_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcontract',
            name='detail',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
