# Generated by Django 4.2.7 on 2023-11-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0008_remove_rentalcontract_detail_delete_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='personal_code',
            field=models.IntegerField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
