# Generated by Django 4.2.7 on 2023-12-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0010_alter_client_personal_code_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
