# Generated by Django 4.2.7 on 2023-12-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0011_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='price',
            new_name='rental_price',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='rental_price',
        ),
    ]
