# Generated by Django 4.2.7 on 2023-12-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0013_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
