# Generated by Django 4.2.7 on 2023-12-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0018_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
