# Generated by Django 4.2.7 on 2023-12-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0019_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalcontract',
            old_name='user',
            new_name='Nuomotojas',
        ),
    ]
