# Generated by Django 4.2.7 on 2023-12-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0020_rename_user_rentalcontract_nuomotojas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalcontract',
            old_name='Nuomotojas',
            new_name='user',
        ),
    ]
