# Generated by Django 4.2.7 on 2023-12-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0021_rename_nuomotojas_rentalcontract_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='vehicle_images', to='CarSell.vehicle'),
        ),
    ]
