# Generated by Django 4.2.7 on 2023-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0023_remove_vehicle_additional_images_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images'),
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
