# Generated by Django 4.2.7 on 2023-12-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0024_vehicle_additional_images_delete_vehicleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='additional_images',
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CarSell.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='CarSell.vehicleimage'),
        ),
    ]
