# Generated by Django 4.2.7 on 2023-12-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0026_remove_vehicle_additional_images_vehicle_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo4',
        ),
    ]
