# Generated by Django 4.2.7 on 2023-12-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0027_remove_vehicle_photo1_remove_vehicle_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos'),
        ),
    ]
