# Generated by Django 4.2.7 on 2023-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0031_remove_rentalcontract_deposit_vehicle_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
