# Generated by Django 4.2.7 on 2023-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarSell', '0032_alter_vehicle_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
